### ISSUE TITLE
Pre-allocate for efficiency ? 

### ISSUE THREAD

**Issue by dynamic-queries** [SciML/OperatorLearning.jl#40]
In [The Forward pass of the Fourier Layer](https://github.com/SciML/OperatorLearning.jl/blob/master/src/FourierLayer.jl#L97-L124), temporary artifacts -  "linear", "𝔉", "i𝔉" are allocated for every call. 

There should be a speedup, if this is preallocated in the form of a "Cache" struct. Is this right ?

**Comment by pzimbrod** [comment]
Yup, that's right. That discussion already came up earlier in #32 and #14. Therefore I'd close this for now as we don't need to track the same thing twice.

Unfortunately due to lack of time and resources, not much has happened on that front. If you're willing, you're welcome to work on that of course!
